# core/tls_decrypt.py
import struct
import binascii
from cryptography.hazmat.primitives.ciphers.aead import AESGCM


class TLSDecryptor:
    """
    Decrypt TLS traffic using SSLKEYLOGFILE secrets.
    Supports TLS 1.2 + TLS 1.3 (AES-GCM).
    """

    def __init__(self, ssl_keylog_path):
        self.secrets = {}
        self._load_keylog(ssl_keylog_path)

    def _load_keylog(self, path):
        """Load SSLKEYLOGFILE generated by browser."""
        try:
            with open(path, "r") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue

                    parts = line.split()
                    if len(parts) != 3:
                        continue

                    label, client_random, secret = parts
                    self.secrets[client_random] = {
                        "label": label,
                        "secret": binascii.unhexlify(secret),
                    }
        except:
            print("[TLS] Unable to load SSLKEYLOGFILE.")

    def decrypt_tls12(self, client_random, encrypted_record):
        """
        Decrypt a TLS 1.2 AES-GCM record.
        """
        if client_random not in self.secrets:
            return None

        secret = self.secrets[client_random]["secret"]

        # TLS record structure:
        # [nonce (8 bytes)] + [explicit IV (8 bytes)] + ciphertext + tag (16 bytes)
        if len(encrypted_record) < 8 + 8 + 16:
            return None

        nonce = encrypted_record[:8]
        explicit = encrypted_record[8:16]
        ciphertext = encrypted_record[16:-16]
        tag = encrypted_record[-16:]

        aesgcm = AESGCM(secret)

        try:
            decrypted = aesgcm.decrypt(nonce + explicit, ciphertext + tag, None)
            return decrypted
        except:
            return None

    def decrypt_tls13(self, client_random, nonce, ciphertext, aad):
        """
        Decrypt a TLS 1.3 record using AES-GCM.
        """
        if client_random not in self.secrets:
            return None

        secret = self.secrets[client_random]["secret"]
        aesgcm = AESGCM(secret)

        try:
            return aesgcm.decrypt(nonce, ciphertext, aad)
        except:
            return None
